# Generated by Django 5.2.1 on 2025-05-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('STOCK', 'Azione'), ('ETF', 'ETF')], max_length=10)),
                ('descrizione', models.TextField(blank=True)),
            ],
        ),
    ]
