# Generated by Django 5.2.1 on 2025-05-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='descrizione',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='tipo',
        ),
        migrations.AddField(
            model_name='asset',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dollaro Americano'), ('EUR', 'Euro')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='asset',
            name='exchange',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='industria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='settore',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='tipo_asset',
            field=models.CharField(blank=True, choices=[('stock', 'Azione'), ('etf', 'ETF')], max_length=10, null=True),
        ),
    ]
