# Generated by Django 5.2.1 on 2025-05-21 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0003_asset_descrizione'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('avg_price', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'asset')},
            },
        ),
    ]
