# Generated by Django 5.2.1 on 2025-06-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfoliotransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliotransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
