# Generated by Django 5.2.1 on 2025-06-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfoliotransaction_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliotransaction',
            name='profit_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
